# -*- coding: utf-8 -*-
"""train2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VvCqgbHh0gxQGwGtmD9DFO6IGJ0Y5qHc

Phase 1 version 2 implementation using GCE
"""

# train_v2.py — Phase 1: Compliant Robust Training
# Only uses PERMITTED augmentations per Hackenza 2026 rules:
# Random Crops, Horizontal Flips, Rotation/Affine, ColorJitter, Cutout/Random Erasing

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import torch.optim as optim
from torch.optim.lr_scheduler import CosineAnnealingLR
from model_submission import RobustClassifier
from google.colab import drive
import os
import random
import numpy as np

# ──────────────────────────────────────────────
# PERMITTED AUGMENTATIONS ONLY
# ──────────────────────────────────────────────
class PermittedAugment:
    """
    Whitelist only:
      - Random horizontal flip
      - Random crop with padding
      - Random rotation / affine
      - ColorJitter (brightness/contrast)
      - Cutout (random erasing)
    """

    def random_flip(self, x):
        if random.random() < 0.5:
            return torch.flip(x, dims=[2])
        return x

    def random_crop(self, x):
        pad = 4
        x_padded = F.pad(x.unsqueeze(0), (pad, pad, pad, pad), mode='reflect').squeeze(0)
        i = random.randint(0, 2 * pad - 1)
        j = random.randint(0, 2 * pad - 1)
        return x_padded[:, i:i+28, j:j+28]

    def random_rotation(self, x):
        angle = random.uniform(-15, 15) * (3.14159 / 180.0)
        cos_a, sin_a = float(np.cos(angle)), float(np.sin(angle))
        theta = torch.tensor([[cos_a, -sin_a, 0.0],
                               [sin_a,  cos_a, 0.0]], dtype=torch.float32)
        grid = F.affine_grid(theta.unsqueeze(0),
                             x.unsqueeze(0).size(),
                             align_corners=False)
        return F.grid_sample(x.unsqueeze(0), grid,
                             align_corners=False,
                             padding_mode='reflection').squeeze(0)

    def color_jitter(self, x):
        brightness = random.uniform(0.7, 1.3)
        contrast   = random.uniform(0.7, 1.3)
        mean = x.mean()
        x = (x * brightness).clamp(0, 1)
        x = ((x - mean) * contrast + mean).clamp(0, 1)
        return x

    def cutout(self, x, length=8):
        h, w = x.shape[1], x.shape[2]
        y  = random.randint(0, h - 1)
        cx = random.randint(0, w - 1)
        y1, y2 = max(0, y - length // 2), min(h, y + length // 2)
        x1, x2 = max(0, cx - length // 2), min(w, cx + length // 2)
        x = x.clone()
        x[:, y1:y2, x1:x2] = 0.0
        return x

    def __call__(self, x):
        x = self.random_flip(x)
        x = self.random_crop(x)
        if random.random() < 0.5:
            x = self.random_rotation(x)
        if random.random() < 0.5:
            x = self.color_jitter(x)
        if random.random() < 0.4:
            x = self.cutout(x)
        return x


class AugmentedDataset(Dataset):
    def __init__(self, images, labels, augment_prob=0.8):
        self.images       = images
        self.labels       = labels
        self.augment      = PermittedAugment()
        self.augment_prob = augment_prob

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        x = self.images[idx].clone()
        y = self.labels[idx]
        if random.random() < self.augment_prob:
            x = self.augment(x)
        return x, y


# ──────────────────────────────────────────────
# GCE LOSS (unchanged)
# ──────────────────────────────────────────────
class GCELoss(nn.Module):
    def __init__(self, q=0.7):
        super().__init__()
        self.q = q

    def forward(self, logits, targets):
        probs        = F.softmax(logits, dim=1)
        target_probs = torch.gather(probs, 1, targets.unsqueeze(1)).squeeze(1)
        loss         = (1.0 - torch.pow(target_probs + 1e-8, self.q)) / self.q
        return loss.mean()


# ──────────────────────────────────────────────
# TRAINING
# ──────────────────────────────────────────────
def train():
    drive.mount('/content/drive')

    DRIVE_BASE  = "/content/drive/My Drive/hackenza-2026-test-time-adaptation-in-the-wild"
    SOURCE_PATH = os.path.join(DRIVE_BASE, "source_toxic.pt")
    SAVE_PATH   = "/content/drive/My Drive/weights_v2.pth"

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Training on: {device}")

    data   = torch.load(SOURCE_PATH)
    images = data['images'].float() / 255.0
    labels = data['labels'].long()
    print(f"Loaded {len(images)} training samples")

    EPOCHS     = 80
    BATCH_SIZE = 128
    LR         = 1e-3

    dataset   = AugmentedDataset(images, labels, augment_prob=0.8)
    loader    = DataLoader(dataset, batch_size=BATCH_SIZE,
                           shuffle=True, drop_last=True, num_workers=2)

    model     = RobustClassifier(num_classes=10).to(device)
    criterion = GCELoss(q=0.7)
    optimizer = optim.Adam(model.parameters(), lr=LR, weight_decay=1e-4)
    scheduler = CosineAnnealingLR(optimizer, T_max=EPOCHS)

    best_loss = float('inf')

    for epoch in range(EPOCHS):
        model.train()
        total_loss, correct, total = 0, 0, 0

        for inputs, targets in loader:
            inputs, targets = inputs.to(device), targets.to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss    = criterion(outputs, targets)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()
            _, predicted = outputs.max(1)
            total   += targets.size(0)
            correct += predicted.eq(targets).sum().item()

        scheduler.step()
        epoch_loss = total_loss / len(loader)
        epoch_acc  = 100. * correct / total
        print(f"Epoch [{epoch+1}/{EPOCHS}] | Loss: {epoch_loss:.4f} | Acc: {epoch_acc:.2f}%")

        if epoch_loss < best_loss:
            best_loss = epoch_loss
            torch.save(model.state_dict(), SAVE_PATH)

    print(f"\nDone. Best weights saved to {SAVE_PATH}")
    print("Update WEIGHTS_PATH in estimate_shift.py and adapt.py to weights_v2.pth")


if __name__ == "__main__":
    torch.manual_seed(42)
    np.random.seed(42)
    random.seed(42)
    train()

!python estimate_shift.py

import torch
import matplotlib.pyplot as plt

DRIVE_BASE = "/content/drive/My Drive/hackenza-2026-test-time-adaptation-in-the-wild"
data = torch.load(f"{DRIVE_BASE}/static.pt")
images = data['images']

print(f"Shape: {images.shape}")
print(f"dtype: {images.dtype}")
print(f"min: {images.min():.3f}, max: {images.max():.3f}, mean: {images.mean():.3f}")

# Visualize 8 samples
fig, axes = plt.subplots(1, 8, figsize=(16, 2))
for i in range(8):
    img = images[i].squeeze()
    if images.max() > 1.0:
        img = img / 255.0
    axes[i].imshow(img, cmap='gray')
    axes[i].axis('off')
plt.suptitle("static.pt samples")
plt.show()

# Quick val accuracy check on weights_v2
import torch
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader
from model_submission import RobustClassifier

DEVICE = torch.device("cuda")
model = RobustClassifier(num_classes=10).to(DEVICE)
model.load_state_dict(torch.load("/content/drive/My Drive/weights_v2.pth", map_location=DEVICE))
model.eval()

data = torch.load(f"{DRIVE_BASE}/val_sanity.pt")
images = data['images'].float() / 255.0
labels = data['labels'].long()
loader = DataLoader(TensorDataset(images, labels), batch_size=256, shuffle=False)

correct, total = 0, 0
with torch.no_grad():
    for imgs, lbls in loader:
        preds = model(imgs.to(DEVICE)).argmax(dim=1).cpu()
        correct += preds.eq(lbls).sum().item()
        total += lbls.size(0)
print(f"Val accuracy (weights_v2): {100.*correct/total:.2f}%")

import torch
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader
from model_submission import RobustClassifier
import numpy as np

DEVICE = torch.device("cuda")
DRIVE_BASE = "/content/drive/My Drive/hackenza-2026-test-time-adaptation-in-the-wild"

# Load adapted model (after Phase 3 BN update)
model = RobustClassifier(num_classes=10).to(DEVICE)
model.load_state_dict(torch.load("/content/drive/My Drive/weights_v2.pth", map_location=DEVICE))
model.eval()

# First do BN stats update on static.pt itself
import torch.nn as nn
data = torch.load(f"{DRIVE_BASE}/static.pt")
images = data['images'].float()
if images.max() > 1.0:
    images = images / 255.0

loader = DataLoader(TensorDataset(images), batch_size=256, shuffle=False)

# Reset and update BN stats
for m in model.modules():
    if isinstance(m, nn.BatchNorm2d):
        m.reset_running_stats()
        m.momentum = None

model.train()
with torch.no_grad():
    for (imgs,) in loader:
        _ = model(imgs.to(DEVICE))
model.eval()

# Now check softmax distribution AFTER BN update
avg_softmax = np.zeros(10)
hard_preds = []
with torch.no_grad():
    for (imgs,) in loader:
        probs = F.softmax(model(imgs.to(DEVICE)), dim=1).cpu().numpy()
        avg_softmax += probs.sum(axis=0)
        hard_preds.extend(probs.argmax(axis=1).tolist())

avg_softmax /= len(images)
classes = ['T-shirt','Trouser','Pullover','Dress','Coat','Sandal','Shirt','Sneaker','Bag','Boot']

print("Avg softmax AFTER BN update:")
for cls, s in zip(classes, avg_softmax):
    print(f"  {cls:<12}: {s:.4f}")

from collections import Counter
print("\nHard prediction counts AFTER BN update:")
for i, cls in enumerate(classes):
    print(f"  {cls:<12}: {Counter(hard_preds)[i]}")

!python adapt.py

!python predict.py